RUNNING: "python -m dask_cuda.cli.dask_cuda_worker --rmm-pool-size=12G
             --local-directory=/tmp/
             --scheduler-file=/root/work/cugraph/mg_utils/dask-scheduler.json
             --memory-limit=auto
             --device-memory-limit=auto
            "
2023-06-22 20:19:57,327 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.33.227.169:39683'
2023-06-22 20:19:57,331 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.33.227.169:46415'
2023-06-22 20:19:57,332 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.33.227.169:35867'
2023-06-22 20:19:57,334 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.33.227.169:35137'
2023-06-22 20:19:57,337 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.33.227.169:38875'
2023-06-22 20:19:57,339 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.33.227.169:41971'
2023-06-22 20:19:57,342 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.33.227.169:41989'
2023-06-22 20:19:57,344 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.33.227.169:46615'
2023-06-22 20:19:58,775 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-06-22 20:19:58,775 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-06-22 20:19:58,852 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-06-22 20:19:58,852 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-06-22 20:19:58,875 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-06-22 20:19:58,875 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-06-22 20:19:58,876 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-06-22 20:19:58,876 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-06-22 20:19:58,876 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-06-22 20:19:58,876 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-06-22 20:19:58,877 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-06-22 20:19:58,877 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-06-22 20:19:58,877 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-06-22 20:19:58,877 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-06-22 20:19:58,880 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-06-22 20:19:58,880 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-06-22 20:19:59,203 - distributed.preloading - INFO - Run preload setup: dask_cuda.initialize
2023-06-22 20:19:59,327 - distributed.preloading - INFO - Run preload setup: dask_cuda.initialize
2023-06-22 20:19:59,329 - distributed.preloading - INFO - Run preload setup: dask_cuda.initialize
2023-06-22 20:19:59,331 - distributed.preloading - INFO - Run preload setup: dask_cuda.initialize
2023-06-22 20:19:59,334 - distributed.preloading - INFO - Run preload setup: dask_cuda.initialize
2023-06-22 20:19:59,335 - distributed.preloading - INFO - Run preload setup: dask_cuda.initialize
2023-06-22 20:19:59,336 - distributed.preloading - INFO - Run preload setup: dask_cuda.initialize
2023-06-22 20:19:59,346 - distributed.preloading - INFO - Run preload setup: dask_cuda.initialize
2023-06-22 20:20:00,930 - distributed.worker - INFO -       Start worker at:  tcp://10.33.227.169:38683
2023-06-22 20:20:00,931 - distributed.worker - INFO -          Listening to:  tcp://10.33.227.169:38683
2023-06-22 20:20:00,931 - distributed.worker - INFO -          dashboard at:        10.33.227.169:37949
2023-06-22 20:20:00,931 - distributed.worker - INFO - Waiting to connect to:   tcp://10.33.227.169:8786
2023-06-22 20:20:00,931 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 20:20:00,931 - distributed.worker - INFO -               Threads:                          1
2023-06-22 20:20:00,931 - distributed.worker - INFO -                Memory:                  62.97 GiB
2023-06-22 20:20:00,931 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-poyy7lb_
2023-06-22 20:20:00,932 - distributed.worker - INFO - Starting Worker plugin RMMSetup-53d9d0e6-520f-48af-9fe6-f6e0cf252384
2023-06-22 20:20:01,126 - distributed.worker - INFO - Starting Worker plugin CPUAffinity-a9285e5e-a413-49ff-b45d-1735a7b30257
2023-06-22 20:20:01,126 - distributed.worker - INFO - Starting Worker plugin PreImport-3727eb11-7031-443d-b3f1-547dfec9d127
2023-06-22 20:20:01,127 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 20:20:01,144 - distributed.worker - INFO -         Registered to:   tcp://10.33.227.169:8786
2023-06-22 20:20:01,145 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 20:20:01,146 - distributed.core - INFO - Starting established connection to tcp://10.33.227.169:8786
2023-06-22 20:20:01,824 - distributed.worker - INFO -       Start worker at:  tcp://10.33.227.169:36141
2023-06-22 20:20:01,825 - distributed.worker - INFO -          Listening to:  tcp://10.33.227.169:36141
2023-06-22 20:20:01,825 - distributed.worker - INFO -          dashboard at:        10.33.227.169:33959
2023-06-22 20:20:01,825 - distributed.worker - INFO - Waiting to connect to:   tcp://10.33.227.169:8786
2023-06-22 20:20:01,825 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 20:20:01,825 - distributed.worker - INFO -               Threads:                          1
2023-06-22 20:20:01,825 - distributed.worker - INFO -                Memory:                  62.97 GiB
2023-06-22 20:20:01,825 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-ife3hm02
2023-06-22 20:20:01,825 - distributed.worker - INFO - Starting Worker plugin CPUAffinity-bc3daefa-3e8b-499e-996e-4767bcc85358
2023-06-22 20:20:01,826 - distributed.worker - INFO - Starting Worker plugin RMMSetup-9db816f3-f6db-483e-b08c-f1c9087b806f
2023-06-22 20:20:01,831 - distributed.worker - INFO -       Start worker at:  tcp://10.33.227.169:40231
2023-06-22 20:20:01,831 - distributed.worker - INFO -          Listening to:  tcp://10.33.227.169:40231
2023-06-22 20:20:01,831 - distributed.worker - INFO -          dashboard at:        10.33.227.169:37477
2023-06-22 20:20:01,831 - distributed.worker - INFO - Waiting to connect to:   tcp://10.33.227.169:8786
2023-06-22 20:20:01,831 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 20:20:01,831 - distributed.worker - INFO -               Threads:                          1
2023-06-22 20:20:01,831 - distributed.worker - INFO -                Memory:                  62.97 GiB
2023-06-22 20:20:01,832 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-cnr36pai
2023-06-22 20:20:01,832 - distributed.worker - INFO - Starting Worker plugin CPUAffinity-0d9096ad-5c1c-4659-899d-0bedece905b2
2023-06-22 20:20:01,832 - distributed.worker - INFO - Starting Worker plugin RMMSetup-daae09dc-34b1-44fe-b544-0379d2560d87
2023-06-22 20:20:01,838 - distributed.worker - INFO -       Start worker at:  tcp://10.33.227.169:40437
2023-06-22 20:20:01,838 - distributed.worker - INFO -          Listening to:  tcp://10.33.227.169:40437
2023-06-22 20:20:01,838 - distributed.worker - INFO -          dashboard at:        10.33.227.169:38073
2023-06-22 20:20:01,839 - distributed.worker - INFO - Waiting to connect to:   tcp://10.33.227.169:8786
2023-06-22 20:20:01,839 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 20:20:01,839 - distributed.worker - INFO -               Threads:                          1
2023-06-22 20:20:01,839 - distributed.worker - INFO -                Memory:                  62.97 GiB
2023-06-22 20:20:01,839 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-iduc377p
2023-06-22 20:20:01,839 - distributed.worker - INFO - Starting Worker plugin CPUAffinity-0022c3ea-e2b0-4a64-b352-cbee5131c147
2023-06-22 20:20:01,839 - distributed.worker - INFO - Starting Worker plugin RMMSetup-5f9cb45b-3130-493a-9613-19b952678917
2023-06-22 20:20:01,844 - distributed.worker - INFO -       Start worker at:  tcp://10.33.227.169:37503
2023-06-22 20:20:01,844 - distributed.worker - INFO -          Listening to:  tcp://10.33.227.169:37503
2023-06-22 20:20:01,844 - distributed.worker - INFO -          dashboard at:        10.33.227.169:36821
2023-06-22 20:20:01,844 - distributed.worker - INFO - Waiting to connect to:   tcp://10.33.227.169:8786
2023-06-22 20:20:01,845 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 20:20:01,845 - distributed.worker - INFO -               Threads:                          1
2023-06-22 20:20:01,845 - distributed.worker - INFO -                Memory:                  62.97 GiB
2023-06-22 20:20:01,845 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-8kqgncco
2023-06-22 20:20:01,845 - distributed.worker - INFO -       Start worker at:  tcp://10.33.227.169:45449
2023-06-22 20:20:01,846 - distributed.worker - INFO -          Listening to:  tcp://10.33.227.169:45449
2023-06-22 20:20:01,846 - distributed.worker - INFO -          dashboard at:        10.33.227.169:44569
2023-06-22 20:20:01,846 - distributed.worker - INFO - Waiting to connect to:   tcp://10.33.227.169:8786
2023-06-22 20:20:01,846 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 20:20:01,846 - distributed.worker - INFO -               Threads:                          1
2023-06-22 20:20:01,846 - distributed.worker - INFO - Starting Worker plugin CPUAffinity-36d5eba3-14ae-4b7f-ae2d-fd170c9c033d
2023-06-22 20:20:01,846 - distributed.worker - INFO -                Memory:                  62.97 GiB
2023-06-22 20:20:01,846 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-tpksxqc3
2023-06-22 20:20:01,846 - distributed.worker - INFO - Starting Worker plugin RMMSetup-786530b0-587c-4f76-8904-349bc2e9088f
2023-06-22 20:20:01,847 - distributed.worker - INFO - Starting Worker plugin PreImport-3ba46344-3aea-43f6-a3f8-60e35a64d166
2023-06-22 20:20:01,847 - distributed.worker - INFO - Starting Worker plugin RMMSetup-c564639f-e227-40c5-8f37-08126e6a4315
2023-06-22 20:20:01,849 - distributed.worker - INFO -       Start worker at:  tcp://10.33.227.169:40197
2023-06-22 20:20:01,849 - distributed.worker - INFO -          Listening to:  tcp://10.33.227.169:40197
2023-06-22 20:20:01,849 - distributed.worker - INFO -          dashboard at:        10.33.227.169:40759
2023-06-22 20:20:01,849 - distributed.worker - INFO - Waiting to connect to:   tcp://10.33.227.169:8786
2023-06-22 20:20:01,849 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 20:20:01,849 - distributed.worker - INFO -               Threads:                          1
2023-06-22 20:20:01,849 - distributed.worker - INFO -                Memory:                  62.97 GiB
2023-06-22 20:20:01,849 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-re53kix4
2023-06-22 20:20:01,850 - distributed.worker - INFO - Starting Worker plugin CPUAffinity-9b8a8dd7-3826-482e-bab9-6e0109c9f6fd
2023-06-22 20:20:01,850 - distributed.worker - INFO - Starting Worker plugin RMMSetup-da1aaaf3-4aaa-4b29-bbd0-9cc74c7d0d5a
2023-06-22 20:20:01,851 - distributed.worker - INFO -       Start worker at:  tcp://10.33.227.169:38673
2023-06-22 20:20:01,851 - distributed.worker - INFO -          Listening to:  tcp://10.33.227.169:38673
2023-06-22 20:20:01,852 - distributed.worker - INFO -          dashboard at:        10.33.227.169:34505
2023-06-22 20:20:01,852 - distributed.worker - INFO - Waiting to connect to:   tcp://10.33.227.169:8786
2023-06-22 20:20:01,852 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 20:20:01,852 - distributed.worker - INFO -               Threads:                          1
2023-06-22 20:20:01,852 - distributed.worker - INFO -                Memory:                  62.97 GiB
2023-06-22 20:20:01,852 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-5jnqq77j
2023-06-22 20:20:01,853 - distributed.worker - INFO - Starting Worker plugin CPUAffinity-43030a65-b6dc-4e38-a5f8-9087f765d01b
2023-06-22 20:20:01,853 - distributed.worker - INFO - Starting Worker plugin RMMSetup-7b2a4771-f240-490f-b14d-15ad72ca6c50
2023-06-22 20:20:02,011 - distributed.worker - INFO - Starting Worker plugin PreImport-af612359-c85c-46c5-925c-18e4c2882a49
2023-06-22 20:20:02,012 - distributed.worker - INFO - Starting Worker plugin PreImport-697b4e9a-39e1-4866-9b33-c84dcfc76ffa
2023-06-22 20:20:02,012 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 20:20:02,012 - distributed.worker - INFO - Starting Worker plugin PreImport-099dfb3b-99fa-4cc1-bfb8-f9da003ef348
2023-06-22 20:20:02,012 - distributed.worker - INFO - Starting Worker plugin PreImport-6d0b89ad-5339-4433-aa01-dbbaf1bb5436
2023-06-22 20:20:02,012 - distributed.worker - INFO - Starting Worker plugin PreImport-a2377d43-9b0d-431e-b99a-64eeafe57109
2023-06-22 20:20:02,013 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 20:20:02,013 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 20:20:02,013 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 20:20:02,013 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 20:20:02,023 - distributed.worker - INFO -         Registered to:   tcp://10.33.227.169:8786
2023-06-22 20:20:02,023 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 20:20:02,024 - distributed.worker - INFO -         Registered to:   tcp://10.33.227.169:8786
2023-06-22 20:20:02,024 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 20:20:02,024 - distributed.core - INFO - Starting established connection to tcp://10.33.227.169:8786
2023-06-22 20:20:02,025 - distributed.worker - INFO -         Registered to:   tcp://10.33.227.169:8786
2023-06-22 20:20:02,025 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 20:20:02,025 - distributed.core - INFO - Starting established connection to tcp://10.33.227.169:8786
2023-06-22 20:20:02,026 - distributed.core - INFO - Starting established connection to tcp://10.33.227.169:8786
2023-06-22 20:20:02,027 - distributed.worker - INFO -         Registered to:   tcp://10.33.227.169:8786
2023-06-22 20:20:02,027 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 20:20:02,028 - distributed.worker - INFO -         Registered to:   tcp://10.33.227.169:8786
2023-06-22 20:20:02,028 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 20:20:02,029 - distributed.core - INFO - Starting established connection to tcp://10.33.227.169:8786
2023-06-22 20:20:02,031 - distributed.core - INFO - Starting established connection to tcp://10.33.227.169:8786
2023-06-22 20:20:02,048 - distributed.worker - INFO - Starting Worker plugin CPUAffinity-f93a2dc7-634a-4a9d-9877-8ff1b9e85569
2023-06-22 20:20:02,048 - distributed.worker - INFO - Starting Worker plugin PreImport-62d98caa-7122-447b-9b3a-42e962bd9d1b
2023-06-22 20:20:02,049 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 20:20:02,049 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 20:20:02,057 - distributed.worker - INFO -         Registered to:   tcp://10.33.227.169:8786
2023-06-22 20:20:02,057 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 20:20:02,058 - distributed.core - INFO - Starting established connection to tcp://10.33.227.169:8786
2023-06-22 20:20:02,060 - distributed.worker - INFO -         Registered to:   tcp://10.33.227.169:8786
2023-06-22 20:20:02,060 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 20:20:02,062 - distributed.core - INFO - Starting established connection to tcp://10.33.227.169:8786
2023-06-22 20:20:02,117 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:20:02,117 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:20:02,117 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:20:02,117 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:20:02,117 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:20:02,117 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:20:02,120 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:20:02,121 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:20:02,194 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-06-22 20:20:02,194 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-06-22 20:20:02,194 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-06-22 20:20:02,194 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-06-22 20:20:02,194 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-06-22 20:20:02,194 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-06-22 20:20:02,194 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-06-22 20:20:02,194 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-06-22 20:20:13,259 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-06-22 20:20:13,269 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-06-22 20:20:13,320 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-06-22 20:20:13,373 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-06-22 20:20:13,384 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-06-22 20:20:13,597 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-06-22 20:20:13,615 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-06-22 20:20:13,637 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-06-22 20:20:19,801 - distributed.core - INFO - Event loop was unresponsive in Worker for 15.97s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-06-22 20:20:19,801 - distributed.core - INFO - Event loop was unresponsive in Worker for 15.98s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-06-22 20:20:19,801 - distributed.core - INFO - Event loop was unresponsive in Worker for 15.98s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-06-22 20:20:19,801 - distributed.core - INFO - Event loop was unresponsive in Worker for 15.98s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-06-22 20:20:19,822 - distributed.core - INFO - Event loop was unresponsive in Worker for 15.99s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-06-22 20:20:19,823 - distributed.core - INFO - Event loop was unresponsive in Worker for 16.00s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-06-22 20:20:19,823 - distributed.core - INFO - Event loop was unresponsive in Worker for 16.00s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-06-22 20:20:19,823 - distributed.core - INFO - Event loop was unresponsive in Worker for 16.00s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-06-22 20:20:54,885 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 20:20:54,885 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 20:20:54,889 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 20:20:54,889 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 20:20:54,889 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 20:20:54,889 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 20:20:54,889 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 20:20:54,889 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 20:20:59,273 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:20:59,274 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:20:59,279 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:20:59,279 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:20:59,279 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:20:59,279 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:20:59,279 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:20:59,279 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:20:59,653 - distributed.worker - WARNING - Compute Failed
Key:       _call_plc_uniform_neighbor_sample-0d630c60-eebf-42e4-b9b8-fc679cdf548a
Function:  _call_plc_uniform_neighbor_sample
args:      (b'\x0b\x1b\x98]\xdf\rJ\x81\xa3\xb1\xa23#b\x06\x85', <pylibcugraph.graphs.MGGraph object at 0x7f9a7c5e2150>, < could not convert arg to str >, True, 8, 0, 9, array([10, 25], dtype=int32), False)
kwargs:    {'weight_t': 'float32', 'with_edge_properties': True, 'random_state': 8731104559153043610, 'return_offsets': False}
Exception: "RuntimeError('non-success value returned from cugraph_uniform_neighbor_sample_with_edge_properties: CUGRAPH_UNKNOWN_ERROR transform: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered')"

2023-06-22 20:25:20,513 - distributed.worker - INFO - Stopping worker at tcp://10.33.227.169:36141. Reason: worker-close
2023-06-22 20:25:20,514 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.33.227.169:35137'. Reason: nanny-close
2023-06-22 20:25:20,516 - distributed.nanny - INFO - Nanny asking worker to close. Reason: nanny-close
2023-06-22 20:25:20,517 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.33.227.169:38875'. Reason: nanny-close
2023-06-22 20:25:20,515 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://10.33.227.169:53048 remote=tcp://10.33.227.169:8786>
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 269, in write
    raise CommClosedError()
distributed.comm.core.CommClosedError
2023-06-22 20:25:20,517 - distributed.nanny - INFO - Nanny asking worker to close. Reason: nanny-close
2023-06-22 20:25:20,518 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.33.227.169:41971'. Reason: nanny-close
2023-06-22 20:25:20,518 - distributed.nanny - INFO - Nanny asking worker to close. Reason: nanny-close
2023-06-22 20:25:20,518 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.33.227.169:41989'. Reason: nanny-close
2023-06-22 20:25:20,519 - distributed.nanny - INFO - Nanny asking worker to close. Reason: nanny-close
2023-06-22 20:25:20,519 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.33.227.169:46615'. Reason: nanny-close
2023-06-22 20:25:20,519 - distributed.nanny - INFO - Nanny asking worker to close. Reason: nanny-close
2023-06-22 20:25:20,519 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.33.227.169:39683'. Reason: nanny-close
2023-06-22 20:25:20,520 - distributed.nanny - INFO - Nanny asking worker to close. Reason: nanny-close
2023-06-22 20:25:20,520 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.33.227.169:46415'. Reason: nanny-close
2023-06-22 20:25:20,520 - distributed.nanny - INFO - Nanny asking worker to close. Reason: nanny-close
2023-06-22 20:25:20,521 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.33.227.169:35867'. Reason: nanny-close
2023-06-22 20:25:20,521 - distributed.nanny - INFO - Nanny asking worker to close. Reason: nanny-close
2023-06-22 20:25:20,540 - distributed.core - ERROR - Timed out during handshake while connecting to tcp://10.33.227.169:46415 after 100 s
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/core.py", line 373, in connect
    handshake = await wait_for(comm.read(), time_left())
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1878, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed)  local=tcp://10.33.227.169:60594 remote=tcp://10.33.227.169:46415>: ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 754, in wrapper
    return await func(*args, **kwargs)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/worker.py", line 1540, in close
    await r.close_gracefully(reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/core.py", line 1362, in send_recv_from_rpc
    comm = await self.pool.connect(self.addr)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/core.py", line 1606, in connect
    return await connect_attempt
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/core.py", line 1527, in _connect
    comm = await connect(
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/core.py", line 378, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.33.227.169:46415 after 100 s
2023-06-22 20:25:23,722 - distributed.nanny - WARNING - Worker process still alive after 3.199987030029297 seconds, killing
2023-06-22 20:25:23,723 - distributed.nanny - WARNING - Worker process still alive after 3.199999389648438 seconds, killing
2023-06-22 20:25:23,724 - distributed.nanny - WARNING - Worker process still alive after 3.199999389648438 seconds, killing
2023-06-22 20:25:23,724 - distributed.nanny - WARNING - Worker process still alive after 3.1999995422363288 seconds, killing
2023-06-22 20:25:23,725 - distributed.nanny - WARNING - Worker process still alive after 3.1999995422363288 seconds, killing
2023-06-22 20:25:23,725 - distributed.nanny - WARNING - Worker process still alive after 3.199999389648438 seconds, killing
2023-06-22 20:25:23,725 - distributed.nanny - WARNING - Worker process still alive after 3.199999389648438 seconds, killing
2023-06-22 20:25:23,726 - distributed.nanny - WARNING - Worker process still alive after 3.1999995422363288 seconds, killing
2023-06-22 20:25:24,517 - distributed.nanny - ERROR - Error in Nanny killing Worker subprocess
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 597, in close
    await self.kill(timeout=timeout, reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 380, in kill
    await self.process.kill(reason=reason, timeout=0.8 * (deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 853, in kill
    await process.join(max(0, deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/process.py", line 330, in join
    await wait_for(asyncio.shield(self._exit_future), timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1878, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2023-06-22 20:25:24,519 - distributed.nanny - ERROR - Error in Nanny killing Worker subprocess
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 597, in close
    await self.kill(timeout=timeout, reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 380, in kill
    await self.process.kill(reason=reason, timeout=0.8 * (deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 853, in kill
    await process.join(max(0, deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/process.py", line 330, in join
    await wait_for(asyncio.shield(self._exit_future), timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1878, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2023-06-22 20:25:24,520 - distributed.nanny - ERROR - Error in Nanny killing Worker subprocess
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 597, in close
    await self.kill(timeout=timeout, reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 380, in kill
    await self.process.kill(reason=reason, timeout=0.8 * (deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 853, in kill
    await process.join(max(0, deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/process.py", line 330, in join
    await wait_for(asyncio.shield(self._exit_future), timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1878, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2023-06-22 20:25:24,520 - distributed.nanny - ERROR - Error in Nanny killing Worker subprocess
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 597, in close
    await self.kill(timeout=timeout, reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 380, in kill
    await self.process.kill(reason=reason, timeout=0.8 * (deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 853, in kill
    await process.join(max(0, deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/process.py", line 330, in join
    await wait_for(asyncio.shield(self._exit_future), timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1878, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2023-06-22 20:25:24,520 - distributed.nanny - ERROR - Error in Nanny killing Worker subprocess
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 597, in close
    await self.kill(timeout=timeout, reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 380, in kill
    await self.process.kill(reason=reason, timeout=0.8 * (deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 853, in kill
    await process.join(max(0, deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/process.py", line 330, in join
    await wait_for(asyncio.shield(self._exit_future), timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1878, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2023-06-22 20:25:24,521 - distributed.nanny - ERROR - Error in Nanny killing Worker subprocess
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 597, in close
    await self.kill(timeout=timeout, reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 380, in kill
    await self.process.kill(reason=reason, timeout=0.8 * (deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 853, in kill
    await process.join(max(0, deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/process.py", line 330, in join
    await wait_for(asyncio.shield(self._exit_future), timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1878, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2023-06-22 20:25:24,521 - distributed.nanny - ERROR - Error in Nanny killing Worker subprocess
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 597, in close
    await self.kill(timeout=timeout, reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 380, in kill
    await self.process.kill(reason=reason, timeout=0.8 * (deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 853, in kill
    await process.join(max(0, deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/process.py", line 330, in join
    await wait_for(asyncio.shield(self._exit_future), timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1878, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2023-06-22 20:25:24,521 - distributed.nanny - ERROR - Error in Nanny killing Worker subprocess
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 597, in close
    await self.kill(timeout=timeout, reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 380, in kill
    await self.process.kill(reason=reason, timeout=0.8 * (deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 853, in kill
    await process.join(max(0, deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/process.py", line 330, in join
    await wait_for(asyncio.shield(self._exit_future), timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1878, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2023-06-22 20:25:24,523 - distributed.process - INFO - reaping stray process <SpawnProcess name='Dask Worker process (from Nanny)' pid=1374046 parent=1374002 started daemon>
2023-06-22 20:25:24,523 - distributed.process - INFO - reaping stray process <SpawnProcess name='Dask Worker process (from Nanny)' pid=1374044 parent=1374002 started daemon>
2023-06-22 20:25:24,523 - distributed.process - INFO - reaping stray process <SpawnProcess name='Dask Worker process (from Nanny)' pid=1374040 parent=1374002 started daemon>
2023-06-22 20:25:24,523 - distributed.process - INFO - reaping stray process <SpawnProcess name='Dask Worker process (from Nanny)' pid=1374037 parent=1374002 started daemon>
2023-06-22 20:25:24,523 - distributed.process - INFO - reaping stray process <SpawnProcess name='Dask Worker process (from Nanny)' pid=1374034 parent=1374002 started daemon>
2023-06-22 20:25:24,523 - distributed.process - INFO - reaping stray process <SpawnProcess name='Dask Worker process (from Nanny)' pid=1374031 parent=1374002 started daemon>
2023-06-22 20:25:24,523 - distributed.process - INFO - reaping stray process <SpawnProcess name='Dask Worker process (from Nanny)' pid=1374028 parent=1374002 started daemon>
2023-06-22 20:25:24,523 - distributed.process - INFO - reaping stray process <SpawnProcess name='Dask Worker process (from Nanny)' pid=1374025 parent=1374002 started daemon>
2023-06-22 20:25:24,807 - distributed.process - WARNING - [<AsyncProcess Dask Worker process (from Nanny)>] process 1374028 exit status was already read will report exitcode 255
2023-06-22 20:25:25,106 - distributed.process - WARNING - [<AsyncProcess Dask Worker process (from Nanny)>] process 1374046 exit status was already read will report exitcode 255
2023-06-22 20:25:25,206 - distributed.process - WARNING - [<AsyncProcess Dask Worker process (from Nanny)>] process 1374044 exit status was already read will report exitcode 255
